---
title: "Week 7"
author: "Cecilia"
date: "5/4/2020"
output: html_document
---

```{r setup, include=FALSE}
library(readxl)
library(tidygraph)
library(tidyverse)
library(ggraph)
 node <- read_excel("~/Downloads/network.xlsx")
 View(node) 

edge <- read_excel("~/Downloads/network.xlsx", 
    sheet = "edge")
 View(edge) 
```

```{r}
commuting.network = tbl_graph(nodes = node,edges = edge,directed = TRUE)

ggraph(commuting.network) + geom_node_point(size = 3) + geom_edge_link(width = 0.5)
``` 


```{r}
ggraph(commuting.network) +geom_edge_link(width = 1, colour = "Red") +geom_node_point(size = 4, colour = "Orange") +geom_node_text(aes(label = label)) +theme_graph()
```


```{r}
ggraph(commuting.network) +geom_edge_link(aes(width = weight), colour = 6) +geom_node_point(size = 4, colour = 3) +geom_node_text(aes(label = label), colour = 1) +theme_graph()
```



```{r}
commuting.network  %>%
  activate(nodes)  %>%
  mutate(centrality = centrality_closeness()) %>% 
  ggraph(layout = "graphopt") + 
  geom_edge_link(aes(width =weight), colour = "lightgray") +
  geom_node_point(aes(size = centrality, colour = centrality)) +
  geom_node_text(aes(label = label), repel = TRUE) +
  scale_color_gradient(low = "yellow", high = "red") +
  theme_graph()
```



```{r}
commuting.network  %>%
  activate(nodes)  %>%
  mutate(centrality = centrality_eigen()) %>% 
  ggraph(layout = "graphopt") + 
  geom_edge_link(aes(width =weight), colour = "lightgray") +
  geom_node_point(aes(size = centrality, colour = centrality)) +
  geom_node_text(aes(label = label), repel = TRUE) +
  scale_color_gradient(low = "yellow", high = "red") +
  theme_graph()
```



```{r}
commuting.network  %>%
  activate(nodes)  %>%
  mutate(centrality = centrality_pagerank()) %>% 
  ggraph(layout = "graphopt") + 
  geom_edge_link(aes(width =weight), colour = "lightgray") +
  geom_node_point(aes(size = centrality, colour = centrality)) +
  geom_node_text(aes(label = label), repel = TRUE) +
  scale_color_gradient(low = "yellow", high = "red") +
  theme_graph()
```

```{r}
commuting.network  %>%
  activate(nodes)  %>%
  mutate(centrality = centrality_betweenness()) %>% 
  ggraph(layout = "graphopt") + 
  geom_edge_link(aes(width =weight), colour = "lightgray") +
  geom_node_point(aes(size = centrality, colour = centrality)) +
  geom_node_text(aes(label = label), repel = TRUE) +
  scale_color_gradient(low = "yellow", high = "red") +
  theme_graph()
```
